// react-demo/src/App.js
import React from 'react'
import { LandingPage } from '@getfoxio/landingpage-react'
import '@getfoxio/landingpage-react/dist/styles.css'

export default function App() {
  return (
    <div className="App">
      <LandingPage
        username={process.env.REACT_APP_USERNAME}
        apiKey={process.env.REACT_APP_API_KEY}
      />
    </div>
  )
}

// landingpage-vue/demo-server/src/App.vue
<script lang="ts">
export default {
  data: () => ({
    username: import.meta.env.VITE_USERNAME,
    apikey: import.meta.env.VITE_APIKEY,
  }),
}
</script>

<template>
  <LandingPage :username="username" :apikey="apikey" />
</template>
<style>
@import 'https://api.getfox.io/static/css/lp.css';
</style>
